version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: monitoring-http
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./targets.yml:/targets.yml
    environment:
      TZ: Asia/Tokyo
      ExecutionInterval: 1
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "root"
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./grafana:/var/lib/grafana